name: Lint Python

on:
  pull_request:
    paths:
      - tracecat/**
      - registry/**
      - tests/**
      - pyproject.toml
      - .github/workflows/lint-python.yml

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/ruff-action@v3
        with:
          src: tracecat/
          version: v0.9.1
          args: check --no-fix

      - uses: astral-sh/ruff-action@v3
        with:
          src: tracecat/
          version: v0.9.1
          args: format --diff
