name: Trigger Tracecat Deployment

on:
  push:
    branches: [main, release]

permissions:
  contents: read
  pull-requests: write

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const context = github.context;

            let env, ref;

            if (context.ref === 'refs/heads/release') {
              env = "production";
              // Fetch the latest release tag
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              if (releases.data.length > 0) {
                ref = releases.data[0].tag_name;
              } else {
                throw new Error('No releases found');
              }
            } else if (context.ref === 'refs/heads/main') {
              env = "staging";
              ref = context.sha;
            } else {
              throw new Error('Unhandled branch context');
            }

            // Send a repository_dispatch event to trigger the Deploy to AWS workflow
            await github.rest.repos.createDispatchEvent({
              owner: 'TracecatHQ',
              repo: 'tracecat-deployment',
              event_type: 'deploy',
              client_payload: {
                'build-env': env,
                'ref': ref
              }
            });
